### ISSUE TITLE
Sylverian Dreamer not showing as owned

### ISSUE THREAD

**Issue by starrwolff** [kevinclement/SimpleArmory#177] opened 2019-08-28 00:13 UTC
Hello,
Just wanted to let you know that I can see that the Sylverian Dreamer has been added to the Simple Armory list, but it doesn't appear to be tracking properly as I do own the dragon and it doesn't show up as being acquired.   I've tried re-logging my game and resetting the page, but over several days it hasn't updated.

Thanks!

**Comment by seirl** [comment] 2019-08-28 07:16
Thanks, closed as duplicate of #171.

**Closed by seirl** 2019-08-28 07:16 UTC
