### ISSUE TITLE
Vashjir Seahorse

### ISSUE THREAD

**Issue by Tauriak** [kevinclement/SimpleArmory#308] opened 2020-11-22 19:23 UTC
I have the mount and am able to use it but I don't have credit for it. How is that fixed?

**Comment by seirl** [comment] 2020-11-22 20:44
Duplicate of #231, #234, #247, #248, #254, #255 and #256 . Please search in the open issues before creating a new one!

**Closed by seirl** 2020-11-22 20:44 UTC
