### ISSUE TITLE
Every Single Incorrect Mount Icon

### ISSUE THREAD

**Issue by Xyrothim** [kevinclement/SimpleArmory#262] opened 2020-06-30 00:38 UTC
This is going to be a full list of (Alliance) mounts that have incorrect icons.
(Some of these are technically correct since icon matches the "drop" icon, but I go by the mount journal)
**------- Battle for Azeroth -------**
Inkscale Deepseeker **(Incorrect)**
Scrapforged Mechaspider **(Incorrect)**
Deepcoral Snapdragon **(Incorrect)**
Honeyback Harvester **(Incorrect)**
Admiralty Stallion **(Item Icon)**
Dapple Gray **(Item Icon)**
Smoky Charger **(Item Icon)**
Rustbolt Resistor **(Incorrect)**
X-995 Mechanocat **(Incorrect)**
Terrified Pack Mule **(Item Icon)**
Goldenmane **(Item Icon)**
Fabious **(Incorrect)**
Rusty Mechanocrawler **(Incorrect)**
Highland Mustang **(Item Icon)**
Lil' Donkey **(Item Icon)**
Kaldorei Nightsaber **(Item Icon)**
Ivory Cloud Serpent **(Incorrect)**
Underrot Crawg **(Item Icon)**
Sharkbait **(Item Icon)**
Mechagon Peacekeeper **(Incorrect)**
Aerial Unit R-21/X **(Incorrect)**
**------- Legion -------**
None!
**------- Draenor -------**
Pale Thorngazer **(Item Icon)**
Deathtusk Felboar (Incorrect, but better wrong)
Smoky Direwolf **(Item Icon)**
--- Mists of Pandaria ---
Spawn of Galakras **(Incorrect)**
Kor'kron War Wolf **(Item Icon)**
**------- Cataclysm -------**
None!
**------- Wrath of the Lich King -------**
None!
**------- The Burning Crusade -------**
None!
**------- Classic -------**
None!
**------- Racial -------**
None!
**------- Professions -------**
Spirit of Eche'ro **(Item Icon)**
Great Sea Ray **(Incorrect)**
Great Northern Elderhorn **(Item Icon)**
Steelbound Devourer **(Item Icon)**
**------- PVP -------**
None! (I'm not sure about glad mounts)
**------- World Events -------**
Infinite Timereaver **(Item Icon)**
Core Hound **(Item Icon)**
Explorer's Dunetrekker **(Incorrect)**
Explorer's Jungle Hopper **(Incorrect)**
(Unsure about TCG, i'm positive they are correct)
**------- Other -------**
None!

**Comment by Rauko** [comment] 2020-07-02 11:41
same problem was with one of DH mounts, but i can't say what - all legion classbound mounts are now missing

**Comment by Xyrothim** [comment] 2020-07-13 06:14
> also incorrect icons has
> Frostwolf Snarler (WoW's 15th Anniversary)
> X-51 Nether-Rocket X-TREME (TCG)
> Blue Drake (WotLK) ?

Blue Drake is correct.
I'm not sure about Frostwolf Snarler because this is an Alliance list, and I am unsure about X-51 Nether-Rocket X-TREME, because I don't have it. Thank you for the contribution!

**Comment by Rauko** [comment] 2020-11-14 19:15
the weird thing is going on with this red TCG rocket - it has one icon for item and other for mount https://prnt.sc/vj7dcr
if site use the item one - it should be changed

and here is snarler https://prnt.sc/vj7fd4

**Comment by seirl** [comment] 2020-11-21 16:55
Icons matching the item are, as far as I can tell, intended behavior. Whether we want to keep that is debatable, but it would be easier if you could separate your list between two categories: 1. incorrect icons and 2. icons that are associated to the item instead of the mount.

**Comment by Xyrothim** [comment] 2020-11-22 08:32
> Icons matching the item are, as far as I can tell, intended behavior. Whether we want to keep that is debatable, but it would be easier if you could separate your list between two categories: 1. incorrect icons and 2. icons that are associated to the item instead of the mount.

I wrote this according to the icons that match the mount journal

**Comment by Roguinaa** [comment] 2020-12-13 21:32
Bump

**Comment by seirl** [comment] 2021-09-12 22:09
New data fixer enforces rigorous matching with the game icons, so these issues should have all been resolved. If you see an icon that's still problematic please open a new issue.

Most icons were fixed in 8a20637887bff0c7ebca868df2dc5c91f045d8b9

**Closed by seirl** 2021-09-12 22:09 UTC
Labels: awaiting reporter feedback
