### ISSUE TITLE
Already Obtained: Grand Black War Mammoth Showing on Mount Plan

### ISSUE THREAD

**Issue by CharmCityNorth** [kevinclement/SimpleArmory#282] opened 2020-09-28 12:46 UTC
I obtained the Reins of the Grand Black War Mammoth years ago, and recently noticed it was added to my Mount Plan even though my character already shows it as obtained.

**Comment by Oath166** [comment] 2020-10-04 13:09
Same issue here for me! And the tracking isn't up to date either.. I'm at 238 in game and on here I'm at 225.

**Comment by seanpeters86** [comment] 2020-10-19 04:41
Same for me as well

**Comment by cmburche** [comment] 2020-10-24 20:10
ditto ^^^

**Comment by Lusolock** [comment] 2020-11-05 12:45
same issue for me

**Comment by jbryson3** [comment] 2020-11-11 06:13
I just ran into this bug so I added a PR to fix it

**Comment by jbryson3** [comment] 2020-11-16 19:58
Dupe of https://github.com/kevinclement/SimpleArmory/issues/271

**Comment by seirl** [comment] 2020-11-21 16:37
Duplicate of #271

**Closed by seirl** 2020-11-21 16:37 UTC
