### ISSUE TITLE
Vashj'ir Seahorse 

### ISSUE THREAD

**Issue by 0rama** [kevinclement/SimpleArmory#255] opened 2020-05-20 14:07 UTC
I have Vashj'ir Seahorse but it is not showing.
example: 
https://simplearmory.com/#/us/frostmourne/bars/collectable/mounts

**Comment by seirl** [comment] 2020-05-20 14:14
Duplicate of #231, #234, #247, #248 and #254.

**Closed by seirl** 2020-05-20 14:14 UTC
