### ISSUE TITLE
Vashj'ir Seahorse not tracked correctly

### ISSUE THREAD

**Issue by gibio123** [kevinclement/SimpleArmory#256] opened 2020-05-25 13:58 UTC
The Cataclysm Quest Mount Vashj'ir Seahorse is not correctly displayed (missing instead of obtained on my profile)
(https:// https://simplearmory.com/#/us/azralon/gibio/collectable/mounts)
Thanks as always for putting in so much effort into this website!

**Comment by seirl** [comment] 2020-05-25 16:42
Duplicate of #231, #234, #247, #248, #254 and #255.

**Closed by seirl** 2020-05-25 16:42 UTC
