### ISSUE TITLE
Blizzard API returns Alliance reputations instead of Horde reputations for Vulperas

### ISSUE THREAD

**Issue by Lorentary** [kevinclement/SimpleArmory#209] opened 2020-01-28 16:29 UTC
Any Vulpera is classified as a strange mix between Horde and Alliance on the Reputation page.
My Lvl 120 Vulpera Shaman, Aranelain (Realm: EU-Twisting Nether) does not show my core Horde reputations. These include all the Horde cities and the Horde BG reputation and possibly others

My personal theory is that it has something to do with the classification of Vulpera because:
1. They are a new race 
2. This happens too for 3 random other Vulpera characters whose name I found on armory.
3. It does not happen to a random Goblin, whom I also found on the Armory nor does it to any of my other characters.

**Comment by seirl** [comment] 2020-01-28 16:41
Yes, I think the race data is just missing.

Should be similar to this fix: https://github.com/kevinclement/SimpleArmory/commit/a45757418f8b06db5c1c7b2e6e076390a29ef718

**Comment by Lorentary** [comment] 2020-01-28 16:49
> Yes, I think the race data is just missing.
> 
> Should be similar to this fix: [a457574](https://github.com/kevinclement/SimpleArmory/commit/a45757418f8b06db5c1c7b2e6e076390a29ef718)

Thanks for the quick reply. I was not sure whether it would be something someone could fix easily as I have not clue about css and html (or javascript... I don't know that is used :p )

**Comment by seirl** [comment] 2020-01-28 16:52
Could you link a Vulpera character where the issue is present so that I can easily check if a fix works?

**Comment by Lorentary** [comment] 2020-01-28 17:02
https://simplearmory.com/#/eu/twisting%20nether/aranelain

**Comment by seirl** [comment] 2020-01-28 17:44
So, I fixed the race data in 1828e92, but amazingly the Blizzard API has a bug that makes it return Alliance reputations instead of Horde ones, so this was actually a Blizzard bug.

**Comment by seirl** [comment] 2020-03-29 11:08
Appears to be fixed in the community API.

**Closed by seirl** 2020-03-29 11:08 UTC
Labels: blizzard, bug
