### ISSUE TITLE
Battle Pets The Maw/Korthia 9.1

### ISSUE THREAD

**Issue by zhyphys** [kevinclement/SimpleArmory#384] opened 2021-08-08 04:39 UTC
Hi, i think that all new Battle Pets for Maw and Korthia and possibly other zones (Desmotereon) on simplearmory are still missing, can you check that? Best regards

**Comment by seirl** [comment] 2021-08-08 12:11
Duplicate of #379

**Closed by seirl** 2021-08-08 12:11 UTC

**Comment by zhyphys** [comment] 2021-08-13 19:21
can this be fixed?

Am So., 8. Aug. 2021 um 14:12 Uhr schrieb Antoine Pietri <
***@***.***>:
