### ISSUE TITLE
Multiple visual mistakes/bugs

### ISSUE THREAD

**Issue by Roguinaa** [kevinclement/SimpleArmory#254] opened 2020-05-18 19:28 UTC
Wrong Icons:
- Fabious (Icon is seahorse)
- Inkscale Deepseeker (icon is seahorse)
- Mechagon Mechanocat (icon is battle pet)
- Both Mechagon spidertanks (I dont even know what icon it is I just know its not the right one)

Other:
- Vashj'r Seahorse missing even on characters that have it

**Comment by seirl** [comment] 2020-05-19 15:41
> Vashj'r Seahorse missing even on characters that have it

This bullet point is a duplicate of #231, #234, #247 and #248.

**Comment by seirl** [comment] 2021-09-12 22:06
New data fixer enforces rigorous matching of icons with the game, so this issue should no longer happen.

**Closed by seirl** 2021-09-12 22:06 UTC
