### ISSUE TITLE
Missing mount: Vashj'ir Seahorse

### ISSUE THREAD

**Issue by JamieTundra** [kevinclement/SimpleArmory#248] opened 2020-05-10 14:53 UTC
The Cataclysm Quest Mount Vashj'ir Seahorse is not correctly displayed (missing instead of obtained on my profile) https://simplearmory.com/#/eu/tarren-mill/tundrapriest/collectable/mounts

**Comment by seirl** [comment] 2020-05-10 15:01
Duplicate of #231, #234, and #247.

**Closed by seirl** 2020-05-10 15:01 UTC
