### ISSUE TITLE
The maw battlepets

### ISSUE THREAD

**Issue by aienia** [kevinclement/SimpleArmory#389] opened 2021-08-28 11:39 UTC
I can´t see a section for the battlepets catchable in the maw! And also, pets that drops from the new raid.

**Comment by amakusa007** [comment] 2021-08-29 21:59
new pets from Korthia, Maw, torghast & tazavesh are not showing yet. these included the ones captures out in the workd and the ones from rewards such as paragon, rares, etc...

**Comment by seirl** [comment] 2021-09-10 22:24
Duplicate of #379

**Closed by seirl** 2021-09-10 22:24 UTC
