### ISSUE TITLE
Haven't been able to fetch my character for months now

### ISSUE THREAD

**Issue by YogSoggoth** [kevinclement/SimpleArmory#241] opened 2020-04-25 07:54 UTC
Йогсоггот - РевущийФьорд (HowlingFjord)
This issue is pretty old by now and it's still not fixed, SimpleArmory can't fetch characters with non-latin letters in their name. It WAS able to fetch them before, though.

**Comment by seirl** [comment] 2020-05-04 19:22
Duplicate of #233

**Closed by seirl** 2020-05-04 19:22 UTC
