### ISSUE TITLE
Missing mount

### ISSUE THREAD

**Issue by Prumper** [kevinclement/SimpleArmory#234] opened 2020-03-27 18:13 UTC
Hello, 
I was looking through my mounts and noticed my quest mount for cataclysm is missing. The Vash'jir seahorse is showing as not obtained on my main character,  but it was on my mage that I obtained it. The only thing I can think is I did race change from blood elf to vulpera. I would love to have that added back please!  Thank you.

**Comment by gmsbaptista** [comment] 2020-03-29 01:27
Can confirm that the Vashj'ir Seahorse is also not showing up on my character https://simplearmory.com/#/eu/chamber-of-aspects/khudan/collectable/mounts

**Comment by evanijr** [comment] 2020-03-29 02:56
Can also confirm it is missing from mine. i also did a faction change from gnome to forsaken i am going to see if i can do the quest on my warlock now if that will change anything however i do still have the mount.

**Comment by seirl** [comment] 2020-03-29 11:05
Duplicate of #231 . Please quickly search in the list of issues before submitting a new one to check if it's not a duplicate.

**Closed by seirl** 2020-03-29 11:05 UTC
