### ISSUE TITLE
Mount Tab is empty

### ISSUE THREAD

**Issue by Imfernus** [kevinclement/SimpleArmory#274] opened 2020-08-04 20:01 UTC
Hi there!
There is something wrong with Mount Tab on my account (all my characters in WOW-account) - it's total empty (Look at Screenshot #1)! It's all OK, for example, with Companions Tab, but not with mounts. Trying to watch Mount Tab of my friend's account - it's OK (Look at Screenshot #2).
![Mount 1](https://user-images.githubusercontent.com/69217504/89339125-50fe9c00-d6a6-11ea-9bdb-d5c1fa2c4f64.png)
![Mount 2](https://user-images.githubusercontent.com/69217504/89339142-565be680-d6a6-11ea-96aa-a1e31b164382.png)

**Comment by seirl** [comment] 2020-08-12 10:02
Duplicate of #273

**Closed by seirl** 2020-08-12 10:02 UTC
