### ISSUE TITLE
Could not fetch

### ISSUE THREAD

**Issue by M7mdsk** [kevinclement/SimpleArmory#225] opened 2020-03-18 16:44 UTC

**Comment by seirl** [comment] 2020-03-18 18:14
Duplicate of #222 . Please read the other issues and be more descriptive when you submit a bug.

**Closed by seirl** 2020-03-18 18:14 UTC

**Comment by M7mdsk** [comment] 2020-03-18 22:01
I meant to say that when i try to check my wow characters armory it keeps on saying error could not fetch and they cant find my character and i tried this with other characters and it keeps on happening. Thank you
