### ISSUE TITLE
Number of Toys in bar missing 2 toys

### ISSUE THREAD

**Issue by gituzzer** [kevinclement/SimpleArmory#421] opened 2022-03-18 10:01 UTC
My toy bar shows 597 / 729 (82%) after update (/sa toys + copy-paste to field).
However, in the game Toy Box, it shows 599/699. 599 is also the number of numbers between [ , , , ] that is copied over to Simple Armory. 
I did not find what are the two toys, if they are missing in the Simple Armory window, I only checked that there are no duplicate numbers.
Could they be two unidentified toys ?

**Comment by seirl** [comment] 2022-03-18 11:46
Could you paste your toy string here? That would help figuring out what the problem is.

**Comment by gituzzer** [comment] 2022-03-18 12:54
[116691,153180,69896,98552,134021,178530,36862,130214,165791,168808,172924,48933,168807,151652,112059,109183,165021,163745,141306,64651,17712,188680,119212,45057,129938,172219,97919,131814,113542,163924,182695,117573,119219,143534,184218,129367,69775,174921,119003,174995,113375,127666,187176,187185,187184,151184,183716,45984,141301,45016,168123,166788,166787,143543,88375,88377,116651,115506,152556,130191,122293,151348,151349,163829,44606,163828,162643,162642,130169,119144,88584,133542,142542,187512,64997,63141,180947,44430,142497,163704,54437,54438,32782,119160,45013,127709,130147,104323,43824,90883,127766,182732,64488,50471,80822,182696,130151,130170,116120,130157,163738,170204,52253,95568,182694,144339,45011,169297,184075,111476,187419,122681,129211,116757,66888,109739,91904,156871,113543,118222,127695,153124,163736,90888,138202,187840,119163,119182,184415,137663,17716,138415,127669,128328,183900,88381,45017,116400,187339,88387,170196,86573,187159,170187,187174,119421,141649,97942,45015,126931,116456,173984,150744,187875,187898,187900,187899,150745,187895,150743,150746,187869,187897,187896,127655,119134,116690,92738,128794,153253,122674,82467,169108,138876,122283,174928,37460,34480,187422,131811,119215,187140,116067,104294,164983,184476,128776,44820,143829,143827,143828,153181,129093,182890,166879,133998,183876,64482,142494,88370,166702,108739,134031,30690,144393,122700,127394,140363,116689,147867,13379,123851,181825,118221,127864,108745,115472,115468,64881,165670,130158,163210,86586,89869,86588,90427,186686,158149,174926,120276,181794,45014,35275,1973,118224,187344,104262,168824,173727,134004,165802,187591,130209,182773,86596,140231,166784,138873,119001,70159,70161,52201,182780,143660,86568,113670,130102,119092,130232,105898,101571,163775,140324,184413,179393,46709,89205,153126,142536,170469,167931,184508,129926,184435,118938,184396,131900,127696,163741,40768,165669,163607,142341,63269,70722,142452,119039,128536,71259,140786,130199,147708,153194,129958,129960,129956,115505,116396,163697,88531,88566,115501,163750,116125,95567,184447,88580,128462,86571,68806,64383,141299,150547,88579,184449,130251,127668,170380,45018,118244,43499,190926,184495,127707,163705,113631,136855,88385,86593,129952,162539,151270,151271,169277,169276,119218,87528,134026,140325,153182,168907,64358,166790,86594,182729,163742,119210,151343,151344,169768,159749,116139,69777,86584,166663,133511,187155,129965,165676,165674,165675,69895,162973,138900,118716,119180,88417,54651,45019,163201,166461,95590,95589,177951,166744,90175,117569,127659,161342,122120,118937,116692,119083,169298,128471,44719,151016,88802,163735,187051,104324,170203,88801,75042,129961,119145,122129,166746,109167,127652,86581,140780,142495,129113,184490,184489,53057,45020,90000,122119,89999,129929,118935,86578,172179,170198,104309,134007,86590,128636,129279,139773,186985,21540,134032,160509,163740,64361,183989,134831,134019,188952,139337,141298,142496,18984,166785,159753,108743,36863,129149,163463,127859,45021,54653,131812,90899,122122,97994,122123,122121,166544,129057,134024,163200,130171,122117,131724,153039,131933,88589,143662,142530,142531,147311,142532,147310,147309,147308,147312,142529,147307,142528,116763,108631,23767,37710,108634,108635,172222,104318,108632,108633,172223,166662,140314,116435,152574,138878,163744,128807,174920,89222,166247,134020,130254,143727,64373,86575,89139,102467,103685,170155,190853,116122,116440,128310,174874,114227,166678,140336,166747,33927,71137,169865,116758,116113,34686,163713,128223,134023,119432,184312,170154,183901,64646,183988,183986,97921,122298,165673,165671,165672,54343,153179,113096,132518,111821,166743,151265,116115,115503,119178,133997,142265,166808,141879,184318,86565,180993,153183,129165,168014,153193,113540,90067,169796,166877,119093,118427,122126,184410,46843,108735,118191,141297,86582,175063,187913,168012,186973,117550,85500,113570,85973,141296,187154,184292,69776,89614,169278,169275,119217,153204,163211,147838,86589,144072,184418,183847,127670,147537,116891,116890,116889,116888,116856,156833,163045]

**Comment by seirl** [comment] 2022-03-18 13:07
Should be fixed, thanks for the report!

**Closed** 2022-03-18 13:06 UTC
