### ISSUE TITLE
New 9.1 achievements, pets and toys not showing

### ISSUE THREAD

**Issue by amakusa007** [kevinclement/SimpleArmory#391] opened 2021-08-29 22:01 UTC
with the release of 9.1 the mount tab has been updated but things like pets, toys and achievement are yet to be updated.

**Comment by Rauko** [comment] 2021-08-30 04:56
https://github.com/kevinclement/SimpleArmory/issues/379

**Comment by seirl** [comment] 2021-09-10 22:24
Duplicate of #379

**Closed by seirl** 2021-09-10 22:24 UTC
